"""Created ItemMod model

Revision ID: 13cd17b02373
Revises: 29bb35bfb675
Create Date: 2023-06-16 12:06:39.520930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13cd17b02373'
down_revision = '29bb35bfb675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_mods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('sub_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_mods_item_id_items')),
    sa.ForeignKeyConstraint(['sub_id'], ['sub_items.id'], name=op.f('fk_item_mods_sub_id_sub_items')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_mods')
    # ### end Alembic commands ###
