"""added gratuity column to checks

Revision ID: 6605da6dbf1b
Revises: 68346d5dbdb7
Create Date: 2023-06-27 13:55:44.669398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6605da6dbf1b'
down_revision = '68346d5dbdb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gratuity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checks', schema=None) as batch_op:
        batch_op.drop_column('gratuity')

    # ### end Alembic commands ###
