"""emp_code changed to a string

Revision ID: 68346d5dbdb7
Revises: 79ca604840a4
Create Date: 2023-06-20 15:21:23.085262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68346d5dbdb7'
down_revision = '79ca604840a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('emp_code',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('emp_code',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
