"""remove nullable in job_code

Revision ID: 79ca604840a4
Revises: 70431c16c553
Create Date: 2023-06-19 20:07:19.162200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79ca604840a4'
down_revision = '70431c16c553'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('job_code',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('job_code',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
