"""added pos_name column to Item and SubItem

Revision ID: 971f1146c8db
Revises: 673005e0b54f
Create Date: 2023-06-15 12:24:45.853916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971f1146c8db'
down_revision = '673005e0b54f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos_name', sa.String(), nullable=False))

    with op.batch_alter_table('sub_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pos_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_items', schema=None) as batch_op:
        batch_op.drop_column('pos_name')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('pos_name')

    # ### end Alembic commands ###
